### ISSUE TITLE
Cannot install NeuroM on macOSX.

### ISSUE THREAD

**Issue by marwan-abdellah** [BlueBrain/NeuroM#1085]
I was unable to install NeuroM on macOSX due to the failure of MorphIO as indicated below. Would there be any solution to resolve that? 
As per the request of Dr. Zisis, I report that the installation fails  on MacBooks with M1 chips and Ventura OS 13! 
Thanks, 

```
 $ ./pip install neurom
Collecting neurom
  Downloading neurom-3.2.4.tar.gz (491 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.0/491.0 kB 1.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting click>=7.0 (from neurom)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: matplotlib>=3.2.1 in /Users/abdellah/.local/lib/python3.10/site-packages (from neurom) (3.7.2)
Collecting morphio>=3.3.6 (from neurom)
  Using cached MorphIO-3.3.6.tar.gz (576 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.8.0 in /Users/abdellah/blender/bbp-blender-3.5/Blender.app/Contents/Resources/3.5/python/lib/python3.10/site-packages (from neurom) (1.26.1)
Requirement already satisfied: pandas>=1.0.5 in /Users/abdellah/.local/lib/python3.10/site-packages (from neurom) (2.1.0)
Collecting pyyaml>=3.10 (from neurom)
  Downloading PyYAML-6.0.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting scipy>=1.2.0 (from neurom)
  Downloading scipy-1.11.3-cp310-cp310-macosx_12_0_arm64.whl.metadata (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.9/112.9 kB 1.3 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.8.4 in /Users/abdellah/blender/bbp-blender-3.5/Blender.app/Contents/Resources/3.5/python/lib/python3.10/site-packages (from neurom) (4.66.1)
Requirement already satisfied: contourpy>=1.0.1 in /Users/abdellah/.local/lib/python3.10/site-packages (from matplotlib>=3.2.1->neurom) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /Users/abdellah/.local/lib/python3.10/site-packages (from matplotlib>=3.2.1->neurom) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/abdellah/.local/lib/python3.10/site-packages (from matplotlib>=3.2.1->neurom) (4.40.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/abdellah/.local/lib/python3.10/site-packages (from matplotlib>=3.2.1->neurom) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /Users/abdellah/.local/lib/python3.10/site-packages (from matplotlib>=3.2.1->neurom) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /Users/abdellah/.local/lib/python3.10/site-packages (from matplotlib>=3.2.1->neurom) (9.5.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /Users/abdellah/.local/lib/python3.10/site-packages (from matplotlib>=3.2.1->neurom) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /Users/abdellah/.local/lib/python3.10/site-packages (from matplotlib>=3.2.1->neurom) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/abdellah/.local/lib/python3.10/site-packages (from pandas>=1.0.5->neurom) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/abdellah/.local/lib/python3.10/site-packages (from pandas>=1.0.5->neurom) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/abdellah/.local/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.2.1->neurom) (1.16.0)
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 2.0 MB/s eta 0:00:00
Downloading PyYAML-6.0.1-cp310-cp310-macosx_11_0_arm64.whl (169 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.3/169.3 kB 1.7 MB/s eta 0:00:00
Downloading scipy-1.11.3-cp310-cp310-macosx_12_0_arm64.whl (29.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.8/29.8 MB 5.2 MB/s eta 0:00:00
Building wheels for collected packages: neurom, morphio
  Building wheel for neurom (pyproject.toml) ... done
  Created wheel for neurom: filename=neurom-3.2.4-py3-none-any.whl size=106089 sha256=83f4aee4f6f693a5c6a3f692a780746b2644634b9e4a4af5d460d51d9c3430d4
  Stored in directory: /Users/abdellah/Library/Caches/pip/wheels/02/e3/f2/388f1ccd7c0b423806a28fccfcc63c77224a8b758934cc5f96
  Building wheel for morphio (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for morphio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [179 lines of output]
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.00-arm64-cpython-310
      creating build/lib.macosx-11.00-arm64-cpython-310/morphio
      copying morphio/__init__.py -> build/lib.macosx-11.00-arm64-cpython-310/morphio
      creating build/lib.macosx-11.00-arm64-cpython-310/morphio/mut
      copying morphio/mut/__init__.py -> build/lib.macosx-11.00-arm64-cpython-310/morphio/mut
      creating build/lib.macosx-11.00-arm64-cpython-310/morphio/vasculature
      copying morphio/vasculature/__init__.py -> build/lib.macosx-11.00-arm64-cpython-310/morphio/vasculature
      running build_ext
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- The C compiler identification is GNU 13.2.0
      -- The CXX compiler identification is GNU 13.2.0
      -- Checking whether C compiler has -isysroot
      -- Checking whether C compiler has -isysroot - yes
      -- Checking whether C compiler supports OSX deployment target flag
      -- Checking whether C compiler supports OSX deployment target flag - yes
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /opt/homebrew/Cellar/gcc/13.2.0/bin/gcc-13 - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Checking whether CXX compiler has -isysroot
      -- Checking whether CXX compiler has -isysroot - yes
      -- Checking whether CXX compiler supports OSX deployment target flag
      -- Checking whether CXX compiler supports OSX deployment target flag - yes
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /opt/homebrew/Cellar/gcc/13.2.0/bin/g++-13 - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      Floating Point Type: float
      -- HDF5 C compiler wrapper is unable to compile a minimal HDF5 program.
      -- Found HDF5: /Users/abdellah/anaconda3/lib/libhdf5.dylib (found version "1.12.1")
      CMake Deprecation Warning at 3rdparty/HighFive/CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
      --   Documentation (doc) cannot be built since Doxygen is not available.
      -- Project 'gsl_lite', package 'gsl-lite' version: '0.40.0'
      -- System name: Darwin
      -- Compiler ID: GNU
      -- CMAKE_CXX_COMPILE_FEATURES: cxx_std_98;cxx_template_template_parameters;cxx_std_11;cxx_alias_templates;cxx_alignas;cxx_alignof;cxx_attributes;cxx_auto_type;cxx_constexpr;cxx_decltype;cxx_decltype_incomplete_return_types;cxx_default_function_template_args;cxx_defaulted_functions;cxx_defaulted_move_initializers;cxx_delegating_constructors;cxx_deleted_functions;cxx_enum_forward_declarations;cxx_explicit_conversions;cxx_extended_friend_declarations;cxx_extern_templates;cxx_final;cxx_func_identifier;cxx_generalized_initializers;cxx_inheriting_constructors;cxx_inline_namespaces;cxx_lambdas;cxx_local_type_template_args;cxx_long_long_type;cxx_noexcept;cxx_nonstatic_member_init;cxx_nullptr;cxx_override;cxx_range_for;cxx_raw_string_literals;cxx_reference_qualified_functions;cxx_right_angle_brackets;cxx_rvalue_references;cxx_sizeof_member;cxx_static_assert;cxx_strong_enums;cxx_thread_local;cxx_trailing_return_types;cxx_unicode_literals;cxx_uniform_initialization;cxx_unrestricted_unions;cxx_user_literals;cxx_variadic_macros;cxx_variadic_templates;cxx_std_14;cxx_aggregate_default_initializers;cxx_attribute_deprecated;cxx_binary_literals;cxx_contextual_conversions;cxx_decltype_auto;cxx_digit_separators;cxx_generic_lambdas;cxx_lambda_init_captures;cxx_relaxed_constexpr;cxx_return_type_deduction;cxx_variable_templates;cxx_std_17;cxx_std_20;cxx_std_23
      CMake Deprecation Warning at binds/python/pybind11/CMakeLists.txt:8 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.


      -- pybind11 v2.10.0
      CMake Warning (dev) at binds/python/pybind11/tools/FindPythonLibsNew.cmake:98 (find_package):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning.

      Call Stack (most recent call first):
        binds/python/pybind11/tools/pybind11Tools.cmake:50 (find_package)
        binds/python/pybind11/tools/pybind11Common.cmake:180 (include)
        binds/python/pybind11/CMakeLists.txt:200 (include)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Found PythonInterp: /Users/abdellah/blender/bbp-blender-3.5/Blender.app/Contents/Resources/3.5/python/bin/python3.10 (found suitable version "3.10.9", minimum required is "3.6")
      -- Found PythonLibs: python3.10
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Failed
      -- Warning: this does not have an effect - use NO_SYSTEM_FROM_IMPORTED if using imported targets
      -- Configuring done (2.5s)
      -- Generating done (0.0s)
      -- Build files have been written to: /private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-install-_ovpw0th/morphio_152c282d264d42c2b98f4368d1e20904/build/temp.macosx-11.00-arm64-cpython-310
      [1/41] Building CXX object src/CMakeFiles/morphio_obj.dir/enums.cpp.o
      [2/41] Building CXX object src/CMakeFiles/morphio_obj.dir/endoplasmic_reticulum.cpp.o
      [3/41] Building CXX object src/CMakeFiles/morphio_obj.dir/mut/endoplasmic_reticulum.cpp.o
      [4/41] Building CXX object src/CMakeFiles/morphio_obj.dir/dendritic_spine.cpp.o
      [5/41] Building CXX object src/CMakeFiles/morphio_obj.dir/glial_cell.cpp.o
      [6/41] Building CXX object src/CMakeFiles/morphio_obj.dir/mito_section.cpp.o
      [7/41] Building CXX object src/CMakeFiles/morphio_obj.dir/mitochondria.cpp.o
      [8/41] Building CXX object src/CMakeFiles/morphio_obj.dir/mut/dendritic_spine.cpp.o
      [9/41] Building CXX object src/CMakeFiles/morphio_obj.dir/mut/glial_cell.cpp.o
      [10/41] Building CXX object src/CMakeFiles/morphio_obj.dir/mut/mito_section.cpp.o
      [11/41] Building CXX object src/CMakeFiles/morphio_obj.dir/point_utils.cpp.o
      [12/41] Building CXX object src/CMakeFiles/morphio_obj.dir/mut/soma.cpp.o
      [13/41] Building CXX object src/CMakeFiles/morphio_obj.dir/errorMessages.cpp.o
      [14/41] Building CXX object src/CMakeFiles/morphio_obj.dir/mut/mitochondria.cpp.o
      [15/41] Building CXX object src/CMakeFiles/morphio_obj.dir/morphology.cpp.o
      [16/41] Building CXX object src/CMakeFiles/morphio_obj.dir/mut/modifiers.cpp.o
      [17/41] Building CXX object src/CMakeFiles/morphio_obj.dir/collection.cpp.o
      [18/41] Building CXX object src/CMakeFiles/morphio_obj.dir/properties.cpp.o
      [19/41] Building CXX object src/CMakeFiles/morphio_obj.dir/soma.cpp.o
      [20/41] Building CXX object src/CMakeFiles/morphio_obj.dir/mut/section.cpp.o
      [21/41] Building CXX object src/CMakeFiles/morphio_obj.dir/version.cpp.o
      [22/41] Building CXX object binds/python/CMakeFiles/_morphio.dir/morphio.cpp.o
      FAILED: binds/python/CMakeFiles/_morphio.dir/morphio.cpp.o
      /opt/homebrew/Cellar/gcc/13.2.0/bin/g++-13 -D_morphio_EXPORTS -isystem /private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-install-_ovpw0th/morphio_152c282d264d42c2b98f4368d1e20904/binds/python/pybind11/include -isystem /Users/abdellah/blender/bbp-blender-3.5/Blender.app/Contents/Resources/3.5/python/include/python3.10 -isystem /private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-install-_ovpw0th/morphio_152c282d264d42c2b98f4368d1e20904/include -isystem /private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-install-_ovpw0th/morphio_152c282d264d42c2b98f4368d1e20904/3rdparty/GSL_LITE/include -isystem /private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-install-_ovpw0th/morphio_152c282d264d42c2b98f4368d1e20904/3rdparty/HighFive/include -isystem /private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-install-_ovpw0th/morphio_152c282d264d42c2b98f4368d1e20904/build/temp.macosx-11.00-arm64-cpython-310/3rdparty/HighFive/include -isystem /Users/abdellah/anaconda3/include -O3 -DNDEBUG -std=gnu++14 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -fPIC -fvisibility=hidden -MD -MT binds/python/CMakeFiles/_morphio.dir/morphio.cpp.o -MF binds/python/CMakeFiles/_morphio.dir/morphio.cpp.o.d -o binds/python/CMakeFiles/_morphio.dir/morphio.cpp.o -c /private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-install-_ovpw0th/morphio_152c282d264d42c2b98f4368d1e20904/binds/python/morphio.cpp
      In file included from /private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-install-_ovpw0th/morphio_152c282d264d42c2b98f4368d1e20904/binds/python/pybind11/include/pybind11/attr.h:13,
                       from /private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-install-_ovpw0th/morphio_152c282d264d42c2b98f4368d1e20904/binds/python/pybind11/include/pybind11/detail/class.h:12,
                       from /private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-install-_ovpw0th/morphio_152c282d264d42c2b98f4368d1e20904/binds/python/pybind11/include/pybind11/pybind11.h:13,
                       from /private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-install-_ovpw0th/morphio_152c282d264d42c2b98f4368d1e20904/binds/python/morphio.cpp:1:
      /private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-install-_ovpw0th/morphio_152c282d264d42c2b98f4368d1e20904/binds/python/pybind11/include/pybind11/detail/common.h:212:10: fatal error: Python.h: No such file or directory
        212 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      [23/41] Building CXX object src/CMakeFiles/morphio_obj.dir/readers/morphologySWC.cpp.o
      [24/41] Building CXX object src/CMakeFiles/morphio_obj.dir/vasc/properties.cpp.o
      [25/41] Building CXX object src/CMakeFiles/morphio_obj.dir/section.cpp.o
      [26/41] Building CXX object src/CMakeFiles/morphio_obj.dir/vasc/section.cpp.o
      [27/41] Building CXX object src/CMakeFiles/morphio_obj.dir/mut/morphology.cpp.o
      [28/41] Building CXX object src/CMakeFiles/morphio_obj.dir/shared_utils.cpp.o
      [29/41] Building CXX object src/CMakeFiles/morphio_obj.dir/vasc/vasculature.cpp.o
      [30/41] Building CXX object src/CMakeFiles/morphio_obj.dir/readers/vasculatureHDF5.cpp.o
      [31/41] Building CXX object src/CMakeFiles/morphio_obj.dir/mut/writers.cpp.o
      [32/41] Building CXX object src/CMakeFiles/morphio_obj.dir/readers/morphologyHDF5.cpp.o
      [33/41] Building CXX object src/CMakeFiles/morphio_obj.dir/readers/morphologyASC.cpp.o
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/Users/abdellah/blender/bbp-blender-3.5/Blender.app/Contents/Resources/3.5/python/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/abdellah/blender/bbp-blender-3.5/Blender.app/Contents/Resources/3.5/python/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/abdellah/blender/bbp-blender-3.5/Blender.app/Contents/Resources/3.5/python/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 69, in <module>
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 369, in run
          self.run_command("build")
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/private/var/folders/kq/xgn53kss4qggy4z71lzwpgjc0000gn/T/pip-build-env-wbgg5rdy/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 28, in run
        File "<string>", line 57, in build_extension
        File "/Users/abdellah/blender/bbp-blender-3.5/Blender.app/Contents/Resources/3.5/python/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', '_morphio', '--config', 'Release']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for morphio
Successfully built neurom
Failed to build morphio
ERROR: Could not build wheels for morphio, which is required to install pyproject.toml-based projects
```

**Comment by mgeplf** [comment]
The above is due to morphio not having the `Python.h` as has been run into here: https://github.com/BlueBrain/MorphIO/issues/446

Could you try this now, we just published a new version which should have the new wheel.

**Comment by mgeplf** [comment]
@marwan-abdellah any luck with this?

**Comment by marwan-abdellah** [comment]
Works like charm now. You can close the ticket. 
Thanks @mgeplf  

```
 $ pip install neurom
Collecting neurom
  Downloading neurom-3.2.5.tar.gz (491 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.2/491.2 kB 3.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: click>=7.0 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from neurom) (8.0.4)
Requirement already satisfied: matplotlib>=3.2.1 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from neurom) (3.7.1)
Requirement already satisfied: morphio>=3.3.6 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from neurom) (3.3.6)
Requirement already satisfied: numpy>=1.8.0 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from neurom) (1.24.3)
Requirement already satisfied: pandas>=1.0.5 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from neurom) (1.5.3)
Requirement already satisfied: pyyaml>=3.10 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from neurom) (6.0)
Requirement already satisfied: scipy>=1.2.0 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from neurom) (1.10.1)
Requirement already satisfied: tqdm>=4.8.4 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from neurom) (4.65.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.1->neurom) (1.0.5)
Requirement already satisfied: cycler>=0.10 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.1->neurom) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.1->neurom) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.1->neurom) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.1->neurom) (23.0)
Requirement already satisfied: pillow>=6.2.0 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.1->neurom) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.1->neurom) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.1->neurom) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from pandas>=1.0.5->neurom) (2022.7)
Requirement already satisfied: six>=1.5 in /Users/abdellah/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib>=3.2.1->neurom) (1.16.0)
Building wheels for collected packages: neurom
  Building wheel for neurom (pyproject.toml) ... done
  Created wheel for neurom: filename=neurom-3.2.5-py3-none-any.whl size=106076 sha256=785b5f5cb1b10a1a1263ea97f81992b13a2941a825b6491cbfa5c6125994abcb
  Stored in directory: /Users/abdellah/Library/Caches/pip/wheels/09/08/15/996e07437d0fc76c34fe34065f1658ac0e3d8af668a40b476f
Successfully built neurom
Installing collected packages: neurom
Successfully installed neurom-3.2.5
```

**Comment by mgeplf** [comment]
Great, thanks for the feedback.
