### ISSUE TITLE
4.0.0: cannot build documentation

### ISSUE THREAD

**Issue by kloczek** [BlueBrain/NeuroM#1123]
Something is wrong (I'm using sphinx 7.3.7)
```console
+ /usr/bin/sphinx-build -n -T -b man doc/source build/sphinx/man
Running Sphinx v7.3.7
making output directory... done
[autosummary] generating autosummary for: api.rst, changelog.rst, cli.rst, definitions.rst, developer.rst, documentation.rst, examples.rst, features.rst, heterogeneous.rst, index.rst, install.rst, license.rst, migration.rst, morph_check.rst, morph_stats.rst, quickstart.rst, spherical_coordinates.rst, tutorial.rst, validation.rst

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autosummary/generate.py", line 503, in generate_autosummary_docs
    name, obj, parent, modname = import_by_name(entry.name)
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autosummary/__init__.py", line 658, in import_by_name
    raise ImportExceptionGroup('no module named %s' % ' or '.join(tried), exceptions)
sphinx.ext.autosummary.ImportExceptionGroup: no module named neurom.check.morphology_checks

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/events.py", line 97, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autosummary/__init__.py", line 818, in process_generate_options
    generate_autosummary_docs(genfiles, suffix=suffix, base_path=app.srcdir,
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autosummary/generate.py", line 508, in generate_autosummary_docs
    name, obj, parent, modname = import_ivar_by_name(entry.name)
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autosummary/__init__.py", line 715, in import_ivar_by_name
    real_name, obj, parent, modname = import_by_name(name, prefixes)
  File "/usr/lib/python3.10/site-packages/sphinx/ext/autosummary/__init__.py", line 658, in import_by_name
    raise ImportExceptionGroup('no module named %s' % ' or '.join(tried), exceptions)
sphinx.ext.autosummary.ImportExceptionGroup: no module named neurom.check

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.10/site-packages/sphinx/application.py", line 268, in __init__
    self._init_builder()
  File "/usr/lib/python3.10/site-packages/sphinx/application.py", line 339, in _init_builder
    self.events.emit('builder-inited')
  File "/usr/lib/python3.10/site-packages/sphinx/events.py", line 108, in emit
    raise ExtensionError(
sphinx.errors.ExtensionError: Handler <function process_generate_options at 0x7f50ee4c5c60> for event 'builder-inited' threw an exception (exception: no module named neurom.check)

Extension error (sphinx.ext.autosummary):
Handler <function process_generate_options at 0x7f50ee4c5c60> for event 'builder-inited' threw an exception (exception: no module named neurom.check)
```

**Comment by mgeplf** [comment]
Ah, it's the `--nitpicky, -n        nit-picky mode: warn about all missing references` option that gives the errors.

**Comment by kloczek** [comment]
Yep .. those warnings are affecting html output. Some parts are highlighted but there is no links.
I'm not affected by those issue because I'm interested only roff output AKA man page but I'm reporting such things as parto f the packaging process 😋

**Comment by mgeplf** [comment]
I think these should be fixed by:
https://github.com/BlueBrain/NeuroM/pull/1124
Perhaps you can test @kloczek?

**Comment by mgeplf** [comment]
Any luck with this @kloczek?

**Comment by mgeplf** [comment]
I think https://github.com/BlueBrain/NeuroM/pull/1124 covers the problems, so I'm going to close this.
If you find more errors, please open a new issue.
