### ISSUE TITLE
morph_stats raises "TypeError: 'numpy.float64' object is not iterable"

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/NeuroM#885]
version: 1.8.0 and 2.0.1.dev8. not reproduced on 1.6.0
OS: Mac OS
Python 3.8.5

used the example data (https://raw.githubusercontent.com/BlueBrain/NeuroM/master/test_data/neurolucida/bio_neuron-000.asc) and another real morphology I cannot put in the ticket.

`morph_stats -f ~/bio_neuron-000.asc`

raises the following error:

Traceback (most recent call last):
  File "/Users/courcol/DEV/hippocampus_morphs/venv3/bin/morph_stats", line 142, in <module>
    main(_args)
  File "/Users/courcol/DEV/hippocampus_morphs/venv3/bin/morph_stats", line 112, in main
    results[neuron.name] = extract_stats(neuron, config)
  File "/Users/courcol/DEV/hippocampus_morphs/venv3/lib/python3.8/site-packages/neurom/apps/morph_stats.py", line 190, in extract_stats
    feature, func = _get_feature_value_and_func(feature_name, neurons)
  File "/Users/courcol/DEV/hippocampus_morphs/venv3/lib/python3.8/site-packages/neurom/features/__init__.py", line 91, in _get_feature_value_and_func
    return np.array(list(feat(obj, **kwargs))), feat
TypeError: 'numpy.float64' object is not iterable

**Comment by mgeplf** [comment]
It appears that the regression was introduced in #860 
@asanin-epfl, can you have a look?
